package com.ivanz851;

import java.util.ArrayList;
import java.util.Random;

public class RandomWordGenerator {
    private static final int ALPHABET_SIZE = 26;
    private static final ArrayList<Character> ALPHABET = new ArrayList<>(ALPHABET_SIZE);

    static {
        for (char letter = 'a'; letter <= 'z'; ++letter) {
            ALPHABET.add(letter);
        }
    }

    private static final String[] WORDS_LIST = {
            "abruptly",
            "absurd",
            "abyss",
            "affix",
            "askew",
            "avenue",
            "awkward",
            "axiom",
            "azure",
            "bagpipes",
            "bandwagon",
            "banjo",
            "bayou",
            "beekeeper",
            "bikini",
            "blitz",
            "blizzard",
            "boggle",
            "bookworm",
            "boxcar",
            "boxful",
            "buckaroo",
            "buffalo",
            "buffoon",
            "buxom",
            "buzzard",
            "buzzing",
            "buzzwords",
            "caliph",
            "cobweb",
            "cockiness",
            "croquet",
            "crypt",
            "curacao",
            "cycle",
            "daiquiri",
            "dirndl",
            "disavow",
            "dizzying",
            "duplex",
            "dwarves",
            "embezzle",
            "equip",
            "espionage",
            "euouae",
            "exodus",
            "faking",
            "fishhook",
            "fixable",
            "fjord",
            "flapjack",
            "flopping",
            "fluffiness",
            "flyby",
            "foxglove",
            "frazzled",
            "frizzled",
            "fuchsia",
            "funny",
            "gabby",
            "galaxy",
            "galvanize",
            "gazebo",
            "giaour",
            "gizmo",
            "glowworm",
            "glyph",
            "gnarly",
            "gnostic",
            "gossip",
            "grogginess",
            "haiku",
            "haphazard",
            "hyphen",
            "iatrogenic",
            "icebox",
            "injury",
            "ivory",
            "ivy",
            "jackpot",
            "jaundice",
            "jawbreaker",
            "jaywalk",
            "jazziest",
            "jazzy",
            "jelly",
            "jigsaw",
            "jinx",
            "jiujitsu",
            "jockey",
            "jogging",
            "joking",
            "jovial",
            "joyful",
            "juicy",
            "jukebox",
            "jumbo",
            "kayak",
            "kazoo",
            "keyhole",
            "khaki",
            "kilobyte",
            "kiosk",
            "kitsch",
            "kiwifruit",
            "klutz",
            "knapsack",
            "larynx",
            "lengths",
            "lucky",
            "luxury",
            "lymph",
            "marquis",
            "matrix",
            "megahertz",
            "microwave",
            "mnemonic",
            "mystify",
            "naphtha",
            "nightclub",
            "nowadays",
            "numbskull",
            "nymph",
            "onyx",
            "ovary",
            "oxidize",
            "oxygen",
            "pajama",
            "peekaboo",
            "phlegm",
            "pixel",
            "pizazz",
            "pneumonia",
            "polka",
            "pshaw",
            "psyche",
            "puppy",
            "puzzling",
            "quartz",
            "queue",
            "quips",
            "quixotic",
            "quiz",
            "quizzes",
            "quorum",
            "razzmatazz",
            "rhubarb",
            "rhythm",
            "rickshaw",
            "schnapps",
            "scratch",
            "shiv",
            "snazzy",
            "sphinx",
            "spritz",
            "squawk",
            "staff",
            "strength",
            "strengths",
            "stretch",
            "stronghold",
            "stymied",
            "subway",
            "swivel",
            "syndrome",
            "thriftless",
            "thumbscrew",
            "topaz",
            "transcript",
            "transgress",
            "transplant",
            "triphthong",
            "twelfth",
            "twelfths",
            "unknown",
            "unworthy",
            "unzip",
            "uptown",
            "vaporize",
            "vixen",
            "vodka",
            "voodoo",
            "vortex",
            "voyeurism",
            "walkway",
            "waltz",
            "wave",
            "wavy",
            "waxy",
            "wellspring",
            "wheezy",
            "whiskey",
            "whizzing",
            "whomever",
            "wimpy",
            "witchcraft",
            "wizard",
            "woozy",
            "wristwatch",
            "wyvern",
            "xylophone",
            "yachtsman",
            "yippee",
            "yoked",
            "youthful",
            "yummy",
            "zephyr",
            "zigzag",
            "zigzagging",
            "zilch",
            "zipper",
            "zodiac",
            "zombie",
    };
    private final Random random = new Random();

    public RandomWordGenerator() {

    }

    public String getRandomWord() {
        int randomIndex = random.nextInt(WORDS_LIST.length);
        return WORDS_LIST[randomIndex];
    }

    public static String getWordByIndex(int wordIndex) {
        return WORDS_LIST[wordIndex];
    }

    public static int getAlphabetSize() {
        return ALPHABET_SIZE;
    }

    public static int getWordsListLength() {
        return WORDS_LIST.length;
    }

    public static ArrayList<Character> getAlphabet() {
        return ALPHABET;
    }
}
